name: Elementals
version: 1.2-beta
main: com.ankoki.elementals.Elementals
api-version: 1.16
author: Ankoki
permissions:
  elementals.admin:
    default: op
    description: The wildcard permission.
  elementals.reload:
    default: op
    description: Allows player's to reload the messages and config.
  elementals.enchant:
    default: op
    description: Allows player's to enchant wands.
  elementals.disenchant:
    default: op
    description: Allows player's to disenchant wands.
  elementals.bypass:
    default: op
    description: Allows player's to bypass cooldowns on spells.
  elementals.give.book:
    default: op
    description: Allows player's to get the enchantable books.
  elementals.help:
    default: op
    description: Allows player's to use the /elementals help command.
  elementals.use.book:
    default: true
    description: Allows player's to combine books with items.
  elementals.cast:
    default: true
    description: Allows player's to cast any spell.
  elementals.cast.generic:
    default: true
    description: Allows player's to cast generic spells.
  elementals.cast.entity:
    default: true
    description: Allows player's to cast entity spells.
  elementals.spell.possession:
    default: true
    description: Ability to cast Possession
  elementals.spell.umbrial:
    default: true
    description: Ability to cast Umbrial.
  elementals.spell.dash:
    default: true
    description: Ability to cast Dash.
  elementals.spell.fireball:
    default: true
    description: Ability to cast Fireball.
  elementals.spell.flow:
    default: true
    description: Ability to cast Flow.
  elementals.spell.medic:
    default: true
    description: Ability to cast Medic.
  elementals.spell.regrowth:
    default: true
    description: Ability to cast Regrowth.
  elementals.spell.rise:
    default: true
    description: Ability to cast Rise.
  elementals.spell.selfdestruct:
    default: true
    description: Ability to cast Self Destruct.
  elementals.spell.travel:
    default: true
    description: Ability to cast Travel.
softdepend:
  - RedLib