name: Elementals
version: 1.1
main: com.ankoki.elementals.Elementals
api-version: 1.16
author: Ankoki
permissions:
  elementals.admin:
    default: op
    description: The wildcard permission.
  elementals.reload:
    default: op
    description: Allows player's to reload the messages and config.
  elementals.enchant:
    default: op
    description: Allows player's to enchant wands.
  elementals.disenchant:
    default: op
    description: Allows player's to disenchant wands.
  elementals.bypass:
    default: op
    description: Allows player's to bypass cooldowns on spells.
  elementals.cast:
    default: true
    description: Allows player's to cast any spell.
  elementals.cast.generic:
    default: true
    description: Allows player's to cast generic spells.
  elementals.cast.entity:
    default: true
    description: Allows player's to cast entity spells.
softdepend:
  - RedLib